// ==UserScript==
// @name         Cloudy's Bazaar Filler
// @namespace    https://github.com/gregapackard/torn-bazaar-filler
// @version      0.9.5
// @description  PDA-first Torn bazaar repricer using cached Weav3r bazaar data, adaptive rate-limit handling, RW/$1 protection, city checks, and Nikeh removal.
// @author       CloudyMuffin440 [4315564]
// @license      MIT
// @match        https://www.torn.com/bazaar.php*
// @match        https://*.torn.com/bazaar.php*
// @run-at       document-idle
// @grant        GM_xmlhttpRequest
// @connect      api.torn.com
// @connect      weav3r.dev
// @updateURL    https://raw.githubusercontent.com/gregapackard/torn-bazaar-filler/main/cloudys-bazaar-filler.user.js
// @downloadURL  https://raw.githubusercontent.com/gregapackard/torn-bazaar-filler/main/cloudys-bazaar-filler.user.js
// ==/UserScript==

(()=>{
'use strict';
const SCRIPT='CloudyBazaarFiller';
const API_KEY_STORAGE='cloudys-bazaar-filler-api-key';
const UNDERCUT_STORAGE='cloudys-bazaar-filler-undercut';
const WEAVER_CACHE_STORAGE='cloudys-bazaar-filler-weaver-cache-v1';
const DEFAULT_UNDERCUT=1;
const NIKEH_ITEMS=new Set([1484,1494,1485,1498,1493,1268]);
const WEAVER_TIMEOUT_MS=10000;
const WEAVER_CACHE_TTL_MS=5*60*1000;
const WEAVER_BASE_GAP_MS=3000;
const WEAVER_SLOW_GAP_MS=6000;
const WEAVER_DEFAULT_RATE_LIMIT_WAIT_MS=20000;
let busy=false,lastWeaverRequestAt=0,weaverGapMs=WEAVER_BASE_GAP_MS;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));

function fireInput(i){i.dispatchEvent(new Event('input',{bubbles:true}));i.dispatchEvent(new Event('change',{bubbles:true}));i.dispatchEvent(new KeyboardEvent('keyup',{bubbles:true,key:'0'}));}
function setControlledInput(i,v){if(!i)return;const d=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value');if(d?.set)d.set.call(i,String(v));else i.value=String(v);fireInput(i);}
function visible(el){if(!el)return false;const r=el.getBoundingClientRect(),s=getComputedStyle(el);return r.width>0&&r.height>0&&s.display!=='none'&&s.visibility!=='hidden';}
function getApiKey(){let k=localStorage.getItem(API_KEY_STORAGE)||'';if(/^[A-Za-z0-9]{16}$/.test(k))return k;k=(prompt("Cloudy's Bazaar Filler\n\nEnter your 16-character Torn PUBLIC/LIMITED API key. It stays in this browser/PDA.")||'').trim();if(!/^[A-Za-z0-9]{16}$/.test(k))throw new Error('A valid 16-character Torn API key is required.');localStorage.setItem(API_KEY_STORAGE,k);return k;}
function getUndercut(){const n=Number(localStorage.getItem(UNDERCUT_STORAGE));return Number.isFinite(n)&&n>=0?Math.floor(n):DEFAULT_UNDERCUT;}
function apiError(msg,status=0,code='REQUEST_FAILED',retryAfterMs=0){const e=new Error(msg);e.status=status;e.code=code;e.retryAfterMs=retryAfterMs;return e;}
function retryAfterMs(headers=''){const m=String(headers).match(/^retry-after:\s*([^\r\n]+)/im);if(!m)return 0;const raw=m[1].trim();const sec=Number(raw);if(Number.isFinite(sec))return Math.max(0,sec*1000);const t=Date.parse(raw);return Number.isFinite(t)?Math.max(0,t-Date.now()):0;}
function requestJson(url,timeout=15000){return new Promise((resolve,reject)=>GM_xmlhttpRequest({method:'GET',url,timeout,onload:r=>{try{if(r.status<200||r.status>=300)throw apiError(`HTTP ${r.status}`,r.status,'HTTP',retryAfterMs(r.responseHeaders));const d=JSON.parse(r.responseText);if(d?.error)reject(apiError(d.error.error||`API error ${d.error.code}`,r.status,'API_ERROR'));else resolve(d);}catch(e){reject(e);}},onerror:()=>reject(apiError('Network error',0,'NETWORK')),ontimeout:()=>reject(apiError('Request timed out',0,'TIMEOUT'))}));}
async function loadRunContext(key){const [itemsData,userData]=await Promise.all([requestJson(`https://api.torn.com/torn/?selections=items&key=${encodeURIComponent(key)}&comment=CloudysBazaarFiller`),requestJson(`https://api.torn.com/user/?selections=basic&key=${encodeURIComponent(key)}&comment=CloudysBazaarFiller`)]);return {items:itemsData?.items||{},playerId:Number(userData?.player_id)||null,key};}
function getItemInfo(items,id){return items?.[id]||items?.[String(id)]||null;}
function getCitySell(items,id){const n=Number(getItemInfo(items,id)?.sell_price);return Number.isFinite(n)&&n>0?n:0;}
function getTornMarketValue(items,id){const n=Number(getItemInfo(items,id)?.market_value);return Number.isFinite(n)&&n>1?n:0;}

function readCache(){try{const x=JSON.parse(localStorage.getItem(WEAVER_CACHE_STORAGE)||'{}');return x&&typeof x==='object'?x:{};}catch{return {};}}
function getCachedWeaver(id){const c=readCache()[String(id)];return c&&Date.now()-Number(c.ts)<WEAVER_CACHE_TTL_MS?c.data:null;}
function putCachedWeaver(id,data){const c=readCache();c[String(id)]={ts:Date.now(),data};for(const [k,v] of Object.entries(c))if(Date.now()-Number(v?.ts)>WEAVER_CACHE_TTL_MS*3)delete c[k];localStorage.setItem(WEAVER_CACHE_STORAGE,JSON.stringify(c));}
async function paceWeaver(){const wait=Math.max(0,weaverGapMs-(Date.now()-lastWeaverRequestAt));if(wait)await sleep(wait);lastWeaverRequestAt=Date.now();}
async function requestWeaverJson(url){let last=null;for(let attempt=0;attempt<3;attempt++){await paceWeaver();try{return await requestJson(url,WEAVER_TIMEOUT_MS);}catch(e){last=e;const rate=e?.status===428||e?.status===429;if(rate){weaverGapMs=WEAVER_SLOW_GAP_MS;const wait=Math.max(e.retryAfterMs||0,WEAVER_DEFAULT_RATE_LIMIT_WAIT_MS*(attempt+1));console.warn(`[${SCRIPT}] Weaver ${e.status}; cooling down ${Math.ceil(wait/1000)}s`);await sleep(wait);}else if(attempt<2){await sleep(2000);}}}const e=apiError(last?.message||'Weaver unavailable',last?.status||0,'WEAVER_UNAVAILABLE',last?.retryAfterMs||0);e.originalCode=last?.code||'';throw e;}

function pickLowestRealPrice(prices,marketPrice=0,bazaarAverage=0){const p=prices.filter(x=>Number.isFinite(x)&&x>1).sort((a,b)=>a-b);if(!p.length)return null;let index=0;if(p.length>=3){const [p0,p1,p2]=p;const refs=[marketPrice,bazaarAverage].filter(x=>Number.isFinite(x)&&x>1);const ref=refs.length?refs.reduce((a,b)=>a+b,0)/refs.length:0;const nextTwoAgree=p1<=p2*1.08,hugeGap=p0<p1*0.40,absurdVsRef=ref>0&&p0<ref*0.35&&p1>=ref*0.65;if(nextTwoAgree&&hugeGap&&absurdVsRef)index=1;}return {base:p[index],index,prices:p};}
async function getWeaverPrice(itemId,ctx){let d=getCachedWeaver(itemId),cached=!!d;if(!d){d=await requestWeaverJson(`https://weav3r.dev/api/marketplace/${encodeURIComponent(itemId)}?limit=100`);if(d&&Array.isArray(d.listings))putCachedWeaver(itemId,d);}if(!d||!Array.isArray(d.listings))throw apiError('Weaver response missing listings',200,'NO_WEAVER_DATA');const marketPrice=Number(d.market_price)||0,bazaarAverage=Number(d.bazaar_average)||0;let listings=d.listings.filter(x=>Number.isFinite(Number(x?.price))&&Number(x.price)>1);if(ctx.playerId)listings=listings.filter(x=>Number(x?.player_id)!==ctx.playerId);const picked=pickLowestRealPrice(listings.map(x=>Number(x.price)),marketPrice,bazaarAverage);if(!picked)throw apiError('Weaver returned no usable bazaar listings',200,'NO_WEAVER_DATA');const listPrice=Math.max(2,Math.floor(picked.base-getUndercut()));return {source:'weaver',targetBase:picked.base,listPrice,marketPrice,bazaarAverage,cached,skippedLowball:picked.index>0,bazaarPremium:marketPrice>1&&listPrice>marketPrice};}
function parseItemMarketListings(data){const root=data?.itemmarket||data?.itemMarket||data?.item_market||data;const rows=Array.isArray(root)?root:(root?.listings||root?.items||root?.results||[]);return (Array.isArray(rows)?rows:[]).map(x=>Number(x?.price)).filter(p=>Number.isFinite(p)&&p>1);}
async function getFallbackPrice(itemId,ctx){const marketValue=getTornMarketValue(ctx.items,itemId);let prices=[];try{const d=await requestJson(`https://api.torn.com/v2/market/${encodeURIComponent(itemId)}/itemmarket?key=${encodeURIComponent(ctx.key)}&limit=100&offset=0`);prices=parseItemMarketListings(d);}catch(e){console.warn(`[${SCRIPT}] Item Market fallback failed ${itemId}`,e);}const picked=pickLowestRealPrice(prices,marketValue,marketValue);let base=picked?.base||0,source='itemmarket';if(!base&&marketValue>1){base=marketValue;source='marketvalue';}if(!base)throw apiError('No safe fallback price',0,'NO_FALLBACK');let listPrice=Math.max(2,Math.floor(base-getUndercut())),fallbackCapped=false;if(marketValue>1){const cap=Math.max(2,Math.floor(marketValue-getUndercut()));if(listPrice>cap){listPrice=cap;fallbackCapped=true;}}return {source,targetBase:base,listPrice,marketValue,fallbackCapped,skippedLowball:!!picked&&picked.index>0};}
async function getSafePrice(itemId,ctx){try{return await getWeaverPrice(itemId,ctx);}catch(e){if(e?.code==='NO_WEAVER_DATA')return getFallbackPrice(itemId,ctx);throw e;}}

function itemIdFrom(el){const img=el?.querySelector('img[src*="/items/"], img');if(!img)return null;const src=img.src||img.getAttribute('src')||'';const m=src.match(/\/items\/(\d+)\//i)||src.match(/\/items\/(\d+)\./i)||src.match(/\/(\d+)\.(?:png|jpg|webp)/i)||src.match(/\/(\d+)\//);return m?Number(m[1]):null;}
function itemName(el){const txt=(el?.innerText||'').split('\n').map(x=>x.trim()).filter(Boolean);return txt.find(x=>!/^x?\d+$/.test(x)&&!/^\$/.test(x))||'item';}
function isRankedWarRow(row){if(!row)return false;const bonus=row.querySelector('[class*="bonus-attachment-"], ul.bonuses-wrap li.bonus [class*="bonus-attachment-"]');const glow=row.querySelector('.glow-yellow,.glow-orange,.glow-red,[class*="glow-yellow"],[class*="glow-orange"],[class*="glow-red"]');const bonusWrap=row.querySelector('ul.bonuses-wrap li.bonus,[class*="bonuses-wrap"] [class*="bonus"]');return !!bonus||!!(glow&&bonusWrap);}
function parseMoneyValue(input){const n=Number(String(input?.value??'').replace(/[$,\s]/g,''));return Number.isFinite(n)?n:0;}
async function waitFor(fn,timeout=2200,interval=40){const end=Date.now()+timeout;while(Date.now()<end){const v=fn();if(v)return v;await sleep(interval);}return null;}
function getManageRows(){const descs=[...document.querySelectorAll('div[data-testid="sortable-item"] div[class*="item___"] div[class*="desc___"], div[class*="row___"] div[class*="item___"] div[class*="desc___"]')];const out=[],seen=new Set();for(const desc of descs){const row=desc.closest('div[data-testid="sortable-item"], div[class*="row___"]')||desc.parentElement?.parentElement;if(!row||!visible(row))continue;const id=itemIdFrom(row);if(!id||seen.has(id))continue;seen.add(id);out.push({row,desc,itemId:id,name:itemName(row)});}return out;}
function getManageButton(row){return row.querySelector('[class*="menuActivators___"] button[class*="iconContainer___"][aria-label="Manage"]')||row.querySelector('button[aria-label="Manage"]')||[...row.querySelectorAll('button')].find(b=>/manage/i.test(b.getAttribute('aria-label')||b.title||''));}
function isManageButtonActive(b){return !!b?.querySelector('span[class*="active___"]')||b?.getAttribute('aria-expanded')==='true';}
function findMobileMenu(row){for(const scope of [row.parentElement,row,document]){const m=scope?.querySelector('[class*="bottomMobileMenu___"]');if(m&&visible(m))return m;}return null;}
function findMobilePriceInput(row){const m=findMobileMenu(row);if(!m)return null;const i=m.querySelector('[class*="priceMobile___"] div.input-money-group input, [class*="priceMobile___"] input');return i&&visible(i)?i:null;}
function findRemoveInput(row){const m=findMobileMenu(row);for(const s of [m,row,row.parentElement].filter(Boolean)){const i=s.querySelector('[class*="remove___"] input, [class*="removeMobile___"] input, input[name*="remove" i]');if(i)return i;}return null;}
function parseListedQty(row,input){const max=Number(input?.max);if(Number.isFinite(max)&&max>0)return Math.floor(max);const text=row?.innerText||'';const hit=text.match(/x\s*([\d,]+)/i)||text.match(/(?:quantity|qty|listed)\D{0,12}([\d,]+)/i);return hit?Number(hit[1].replace(/,/g,'')):1;}
async function openManageRow(entry){let input=findMobilePriceInput(entry.row);if(input)return {input,button:getManageButton(entry.row),openedByUs:false};const button=getManageButton(entry.row);if(!button)throw new Error('Manage button not found');const active=isManageButtonActive(button);if(!active)button.click();input=await waitFor(()=>findMobilePriceInput(entry.row));if(!input)throw new Error('Mobile price panel did not open');return {input,button,openedByUs:!active};}
async function closeManageRow(h){if(h?.openedByUs&&h.button){h.button.click();await sleep(100);}}
async function markForRemoval(entry){const i=await waitFor(()=>findRemoveInput(entry.row),1000,40);if(!i)throw new Error('Remove quantity input not found');const q=parseListedQty(entry.row,i);setControlledInput(i,q);return q;}
function failureKey(e){if(e?.code==='WEAVER_UNAVAILABLE')return e.status?`HTTP ${e.status}`:(e.originalCode||'network');return 'other';}
function bumpFailure(m,k){m[k]=(m[k]||0)+1;}
function formatFailures(m){return Object.entries(m).map(([k,v])=>`${k}:${v}`).join(', ');}

async function fillManagePage(ctx){const rows=getManageRows();if(!rows.length)return null;let repriced=0,removed=0,nikehRemoved=0,skipped=0,weaverUnavailable=0,rwSkipped=0,dollarSkipped=0,fallback=0,fallbackCapped=0,bazaarPremium=0,lowballsSkipped=0,cached=0;const failureReasons={};for(let i=0;i<rows.length;i++){if(isRankedWarRow(rows[i].row)){rwSkipped++;continue;}setButtonState(`OPENING ${i+1}/${rows.length}…`,true);let h=null;try{h=await openManageRow(rows[i]);if(parseMoneyValue(h.input)===1){dollarSkipped++;continue;}if(NIKEH_ITEMS.has(rows[i].itemId)){await markForRemoval(rows[i]);nikehRemoved++;removed++;continue;}setButtonState(`PRICING ${i+1}/${rows.length}…`,true);const safe=await getSafePrice(rows[i].itemId,ctx);if(safe.cached)cached++;if(safe.source!=='weaver')fallback++;if(safe.fallbackCapped)fallbackCapped++;if(safe.bazaarPremium)bazaarPremium++;if(safe.skippedLowball)lowballsSkipped++;const city=getCitySell(ctx.items,rows[i].itemId);if(city>safe.listPrice){await markForRemoval(rows[i]);removed++;}else{setControlledInput(h.input,safe.listPrice);repriced++;}}catch(e){if(e?.code==='WEAVER_UNAVAILABLE'){weaverUnavailable++;bumpFailure(failureReasons,failureKey(e));}else skipped++;console.warn(`[${SCRIPT}] ${rows[i].name} (${rows[i].itemId})`,e);}finally{await closeManageRow(h);}}return {mode:'manage',repriced,removed,nikehRemoved,skipped,weaverUnavailable,rwSkipped,dollarSkipped,fallback,fallbackCapped,bazaarPremium,lowballsSkipped,cached,failureReasons,total:rows.length};}
function getAddRows(){return [...document.querySelectorAll('ul.items-cont li.clearfix, div[class*="itemsContainner___"] div[class*="item___"], div[class*="rowItems___"] div[class*="item___"]')].filter(r=>visible(r)&&r.querySelector('div.amount-main-wrap, div[class*="amount___"]')&&itemIdFrom(r));}
function addControls(row){const amount=row.querySelector('div.amount-main-wrap, div[class*="amount___"]'),price=row.querySelector('div.price, div[class*="price___"]');if(!amount||!price)return null;const checkbox=amount.querySelector('input[type="checkbox"]'),qty=checkbox?null:amount.querySelector('input'),priceInputs=[...price.querySelectorAll('input')],id=itemIdFrom(row);return id&&(checkbox||qty)&&priceInputs.length?{row,checkbox,qty,priceInputs,itemId:id}:null;}
function maxQty(c){if(c.checkbox)return 1;const m=Number(c.qty?.max);if(Number.isFinite(m)&&m>0)return Math.floor(m);const text=c.row.innerText||'',hit=text.match(/x\s*([\d,]+)/i)||text.match(/(?:owned|available|max)\D{0,12}([\d,]+)/i);return hit?Number(hit[1].replace(/,/g,'')):null;}
async function fillAddPage(ctx){const rows=getAddRows().map(addControls).filter(Boolean);if(!rows.length)return null;let filled=0,cityBetter=0,nikehSkipped=0,skipped=0,weaverUnavailable=0,rwSkipped=0,dollarSkipped=0,fallback=0,fallbackCapped=0,bazaarPremium=0,lowballsSkipped=0,cached=0;const failureReasons={};for(let i=0;i<rows.length;i++){if(isRankedWarRow(rows[i].row)){rwSkipped++;continue;}if(rows[i].priceInputs.some(x=>parseMoneyValue(x)===1)){dollarSkipped++;continue;}if(NIKEH_ITEMS.has(rows[i].itemId)){nikehSkipped++;continue;}setButtonState(`FILLING ${i+1}/${rows.length}…`,true);try{const q=maxQty(rows[i]);if(!q){skipped++;continue;}const safe=await getSafePrice(rows[i].itemId,ctx);if(safe.cached)cached++;if(safe.source!=='weaver')fallback++;if(safe.fallbackCapped)fallbackCapped++;if(safe.bazaarPremium)bazaarPremium++;if(safe.skippedLowball)lowballsSkipped++;const city=getCitySell(ctx.items,rows[i].itemId);if(city>safe.listPrice){cityBetter++;continue;}if(rows[i].checkbox&&!rows[i].checkbox.checked)rows[i].checkbox.click();else if(rows[i].qty)setControlledInput(rows[i].qty,q);rows[i].priceInputs.forEach(x=>setControlledInput(x,safe.listPrice));filled++;}catch(e){if(e?.code==='WEAVER_UNAVAILABLE'){weaverUnavailable++;bumpFailure(failureReasons,failureKey(e));}else skipped++;console.warn(`[${SCRIPT}] add ${rows[i].itemId}`,e);}}return {mode:'add',filled,cityBetter,nikehSkipped,skipped,weaverUnavailable,rwSkipped,dollarSkipped,fallback,fallbackCapped,bazaarPremium,lowballsSkipped,cached,failureReasons,total:rows.length};}
function setButtonState(text,disabled=false){const b=document.getElementById('cbf-fill-page');if(!b)return;b.textContent=text;b.disabled=disabled;b.style.opacity=disabled?'.7':'1';}
function toast(msg,type='ok'){let b=document.getElementById('cbf-toast');if(!b){b=document.createElement('div');b.id='cbf-toast';Object.assign(b.style,{position:'fixed',left:'12px',right:'12px',bottom:'76px',zIndex:'2147483647',padding:'11px 14px',borderRadius:'10px',fontSize:'13px',fontWeight:'700',textAlign:'center',color:'#fff',boxShadow:'0 4px 14px rgba(0,0,0,.35)',pointerEvents:'none'});document.body.appendChild(b);}b.style.background=type==='error'?'#a82c2c':type==='warn'?'#8a6515':'#287842';b.textContent=msg;b.style.opacity='1';clearTimeout(b._t);b._t=setTimeout(()=>b.style.opacity='0',14000);}
async function fillPage(){if(busy)return;busy=true;weaverGapMs=WEAVER_BASE_GAP_MS;setButtonState('LOADING PRICES…',true);try{const ctx=await loadRunContext(getApiKey());let r=await fillManagePage(ctx);if(!r)r=await fillAddPage(ctx);if(!r){toast('No editable Bazaar rows found on this screen.','warn');return;}const bits=[];if(r.mode==='manage')bits.push(`${r.repriced} repriced`,`${r.removed} removal`);else bits.push(`${r.filled} filled`);if(r.cached)bits.push(`${r.cached} cached`);if(r.nikehRemoved)bits.push(`${r.nikehRemoved} Nikeh`);if(r.nikehSkipped)bits.push(`${r.nikehSkipped} Nikeh skipped`);if(r.cityBetter)bits.push(`${r.cityBetter} city better`);if(r.bazaarPremium)bits.push(`${r.bazaarPremium} bazaar premium`);if(r.fallback)bits.push(`${r.fallback} genuine fallback`);if(r.fallbackCapped)bits.push(`${r.fallbackCapped} fallback capped`);if(r.lowballsSkipped)bits.push(`${r.lowballsSkipped} extreme lowball ignored`);if(r.weaverUnavailable){const why=formatFailures(r.failureReasons);bits.push(`${r.weaverUnavailable} Weaver unavailable${why?` (${why})`:''}`);}if(r.rwSkipped)bits.push(`${r.rwSkipped} RW skipped`);if(r.dollarSkipped)bits.push(`${r.dollarSkipped} $1 skipped`);if(r.skipped)bits.push(`${r.skipped} untouched`);toast(bits.join(' • ')+(r.mode==='manage'?'. Review, then tap SAVE CHANGES.':''),(r.weaverUnavailable||r.skipped)?'warn':'ok');}catch(e){console.error(`[${SCRIPT}]`,e);toast(e.message||'Fill failed.','error');}finally{busy=false;setButtonState('FILL THIS PAGE');}}
function injectUI(){if(document.getElementById('cbf-fill-page'))return;const w=document.createElement('div');w.id='cbf-wrap';Object.assign(w.style,{position:'fixed',left:'10px',right:'10px',bottom:'12px',zIndex:'2147483646',display:'flex',gap:'8px',alignItems:'stretch',maxWidth:'680px',margin:'0 auto'});const b=document.createElement('button');b.id='cbf-fill-page';b.type='button';b.textContent='FILL THIS PAGE';Object.assign(b.style,{flex:'1 1 auto',minHeight:'52px',border:'0',borderRadius:'12px',background:'linear-gradient(180deg,#2f9b56,#247642)',color:'#fff',fontSize:'16px',fontWeight:'900',letterSpacing:'.3px',boxShadow:'0 4px 16px rgba(0,0,0,.4)',touchAction:'manipulation'});b.addEventListener('click',fillPage);const g=document.createElement('button');g.type='button';g.textContent='⚙';Object.assign(g.style,{width:'52px',minHeight:'52px',border:'0',borderRadius:'12px',background:'#333',color:'#fff',fontSize:'22px',fontWeight:'700',boxShadow:'0 4px 16px rgba(0,0,0,.4)',touchAction:'manipulation'});g.addEventListener('click',()=>{const v=prompt('Undercut the chosen competing price by how many dollars?',String(getUndercut()));if(v===null)return;const n=Number(v.replace(/,/g,'').trim());if(!Number.isFinite(n)||n<0)return toast('Enter a valid non-negative dollar amount.','error');localStorage.setItem(UNDERCUT_STORAGE,String(Math.floor(n)));toast(`Undercut set to $${Math.floor(n).toLocaleString()}.`);});w.append(b,g);document.body.appendChild(w);}
function boot(){injectUI();new MutationObserver(injectUI).observe(document.documentElement,{childList:true,subtree:true});console.log(`[${SCRIPT}] Loaded v0.9.5`);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();